parsers:
  - janat-t/janat-traefik-logs
collections:
  - crowdsecurity/base-http-scenarios
description: "traefik support: parser and generic http scenarios"
author: janat-t
tags:
  - traefik
  - http
  - bruteforce

