parsers:
  - ./parsers/s01-parse/janat-t/janat-traefik-logs.yaml
  - crowdsecurity/syslog-logs
  - crowdsecurity/dateparse-enrich
  - crowdsecurity/http-logs
scenarios:
- ""
postoverflows:
- ""
log_file: janat-traefik-logs.log
log_type: traefik
labels: {}
ignore_parsers: false
